#https://catalog.redhat.com/en/software/containers/rhel10/s2i-core/677cf8035fdd0fab2f79e70a#overview
FROM quay.io/agentfox/sandbox:latest

USER root

ARG TARGETARCH

ENV ARCH=${TARGETARCH:-arm64} \
    HOME=/opt/app-root/src \
    WORKSPACE=/opt/app-root/src \
    APP_ROOT=/opt/app-root \
    XDG_CONFIG_HOME=/opt/app-root/.config 

# set the virtual environment
ENV UV_PYTHON=python3.14 VIRTUAL_ENV=/venv

# install python dependencies
COPY containers/agents/requirements.txt /tmp/requirements.txt

RUN uv venv --clear /venv && \
    uv pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

# install the agents here

# install nightshift agent
RUN curl -fsSL https://raw.githubusercontent.com/agent-fox-dev/nightshift/refs/heads/main/install.sh | sh

# install agent-fox agent
RUN curl -fsSL https://raw.githubusercontent.com/agent-fox-dev/agent-fox/refs/heads/main/install.sh | sh

# clean up
RUN dnf -y clean all --enablerepo='*' && \
    rm -rf /var/cache/dnf

# Reset permissions of modified directories
RUN rpm-file-permissions && chown -R 1001:0 ${APP_ROOT}

# Directory with the sources is set as the working directory so all STI scripts
# can execute relative to this path.
WORKDIR ${WORKSPACE}