apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-hub-config
  labels:
    app.kubernetes.io/name: af-hub
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-hub-data
  labels:
    app.kubernetes.io/name: af-hub
    app.kubernetes.io/component: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
