apiVersion: v1
kind: Secret
metadata:
  name: af-hub-secrets
  labels:
    app.kubernetes.io/name: af-hub
    app.kubernetes.io/component: server
type: Opaque
stringData:
  admin-email: "CHANGE_ME"
  admin-token: "CHANGE_ME"
  github-client-id: "CHANGE_ME"
  github-client-secret: "CHANGE_ME"