name: agentfox hub container build

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build-hub-container:
    uses: ./.github/workflows/inc-build-hub.yaml
    with:
      container_name: hub
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write
