name: container build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-hub-container:
    uses: ./.github/workflows/build.yaml
    with:
      container_name: hub
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write
