name: build the sandbox containers

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-sandbox-container:
    uses: ./.github/workflows/inc-build.yaml
    with:
      container_name: sandbox
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

  build-agents-container:
    uses: ./.github/workflows/inc-build.yaml
    needs: [build-sandbox-container]
    with:
      container_name: agents
    secrets: inherit
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write